export const FARMACOS = [
    {codATC:"",descATC:"SELECCIONE UN FÁRMACO"},
    {codATC:"01",descATC:"ALGODON"},
    {codATC:"01A",descATC:"ALGODON ARROLLADO"},
    {codATC:"01A01",descATC:"ALGODON ARROLLADO PURO"},
    {codATC:"01A0101",descATC:"ALGODON ARROLLADO PURO"},
    {codATC:"01A02",descATC:"ALGODON ARROLLADO MEZCLA"},
    {codATC:"01A0201",descATC:"ALGODON ARROLLADO MEZCLA"},
    {codATC:"01B",descATC:"ALGODON EN RAMA"},
    {codATC:"01B02",descATC:"ALGODON RAMA MEZCLA"},
    {codATC:"01B0201",descATC:"ALGODON RAMA MEZCLA"},
    {codATC:"01C",descATC:"ALGODON EN ZIG-ZAG"},
    {codATC:"01C01",descATC:"ALGODON ZIC-ZAG PURO"},
    {codATC:"01C0101",descATC:"ALGODON ZIC-ZAG PURO"},
    {codATC:"01C02",descATC:"ALGODON ZIG-ZAG MEZCLA"},
    {codATC:"01C0201",descATC:"ALGODON ZIG-ZAG MEZCLA"}
]